<ul class="col-md-7 col-lg-5 pull-lg-4 left list">
    <li class="dropdown">
        <button class="dropbtn" id="dr1"><i class="fa fa-user"></i><span>My account</span><i class="fa fa-angle-down"></i></button>
        <div class="dropdown-content left dr1">
            <a href="#">Link 1</a>
            <a href="#">Link 2</a>
            <a href="#">Link 3</a>
        </div>
    </li>
    <li><a href=""><i class="fa fa-arrow-circle-o-up"></i><span>Checkout</span></a></li>
    <li><a href=""><i class="fa fa-heart"></i><span>Wishlist</span></a></li>
    <li><a href=""><i class="fa fa-random"></i><span>Compare</span></a></li>
	<?php $_links = $this->getLinks(); ?>
	<?php if(count($_links)>0): ?>
	<div class="links">
		<?php if($this->getTitle()): ?>
		<div class="block-title"><strong><span><?php echo $this->__($this->getTitle()); ?></span></strong></div>
		<?php endif; ?>
		<ul<?php if($this->getName()): ?> id="<?php echo $this->getName() ?>"<?php endif;?>>
			<?php foreach($_links as $_link): ?>
				<?php if ($_link instanceof Mage_Core_Block_Abstract):?>
					<?php echo $_link->toHtml() ?>
				<?php else: ?>
					<li<?php if($_link->getIsFirst()||$_link->getIsLast()): ?> class="<?php if($_link->getIsFirst()): ?>first<?php endif; ?><?php if($_link->getIsLast()): ?> last<?php endif; ?>"<?php endif; ?> <?php echo $_link->getLiParams() ?>><?php echo $_link->getBeforeText() ?><a href="<?php echo $_link->getUrl() ?>" title="<?php echo $_link->getTitle() ?>" <?php echo $_link->getAParams() ?>><?php echo $_link->getLabel() ?></a><?php echo $_link->getAfterText() ?></li>
				<?php endif;?>
			<?php endforeach; ?>
		</ul>
	</div>
	<?php endif; ?>
</ul>