<ul class="col-md-7 col-lg-5 pull-lg-4 left list">
    <li class="dropdown">
        <button class="dropbtn" id="dr1"><i class="fa fa-user"></i><span>My account</span><i class="fa fa-angle-down"></i></button>
        <div class="dropdown-content left dr1">
            <?php echo $this->getChildHTML('account-block') ?>
        </div>
    </li>
    <?php echo $this->getChildHtml('checkout-block') ?>
    <?php echo $this->getChildHTML('wishlist-block') ?>
	<?php echo $this->getChildHTML('compare-block') ?>
	
</ul>