<div class="footerlist category col-12 col-sm-6 col-lg-2">
    <p>CATEGORY</p>
    <ul>
        <li><a href=""><i class="fa fa-caret-right"></i>Women</a></li>
        <li><a href=""><i class="fa fa-caret-right"></i>Men Sale</a></li>
        <li><a href=""><i class="fa fa-caret-right"></i>Jewellery</a></li>
        <li><a href=""><i class="fa fa-caret-right"></i>Accessories</a></li>
        <li><a href=""><i class="fa fa-caret-right"></i>Sunglass</a></li>
        <li><a href=""><i class="fa fa-caret-right"></i>Site map</a></li>
    </ul>
</div>