<div class="contact col-sm-6 col-lg-3">
    <p>CONTACT US</p>
    <ul>
        <li><span><i class="fa fa-map-marker"></i></span><a class="map">Rongmohl tower 34 New  City 2154, Bali road MPB.</a></li>
        <li><span><i class="fa fa-skype"></i></span><a>Eshop</a></li>
        <li><span><i class="fa fa-phone"></i></span><a>2(402)234-85467</a></li>
        <li><span><i class="fa fa-envelope"></i></span><a>support@Eshop.com</a></li>
    </ul>
</div>