<div class="shop col-12 col-lg-3">
    <p><img src="<?php echo $this->getSkinUrl('images/icon_footer.png')?>"></p>
    <span>Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using  Content here content here.</span>
    <br>
    <a href=""><i class="fa fa-facebook"></i></a>
    <a href=""><i class="fa fa-twitter"></i></a>
    <a href=""><i class="fa fa-google-plus"></i></a>
    <a href=""><i class="fa fa-linkedin"></i></a>
    <a href=""><i class="fa fa-skype"></i></a>
</div>