<div class="footerlist information col-12 col-sm-6 col-lg-2">
    <p>INFORMATION</p>
    <ul>
        <li><a href=""><i class="fa fa-caret-right"></i>About Us</a></li>
        <li><a href=""><i class="fa fa-caret-right"></i>Delivery Information</a></li>
        <li><a href=""><i class="fa fa-caret-right"></i>Privacy Policy</a></li>
        <li><a href=""><i class="fa fa-caret-right"></i>Terms & Conditions</a></li>
        <li><a href=""><i class="fa fa-caret-right"></i>Help</a></li>
        <li><a href=""><i class="fa fa-caret-right"></i>Location</a></li>
    </ul>
</div>