<div class="footerlist account col-12 col-sm-6 col-lg-2">
    <p>MY ACCOUNT</p>
    <ul>
        <?php $_links = $this->getLinks(); ?>
		<?php foreach($_links as $_link): ?>
			<?php if ($_link instanceof Mage_Core_Block_Abstract):?>
				<?php echo $_link->toHtml() ?>
			<?php else: ?>
				<li><a href="<?php echo $_link->getUrl() ?>" title="<?php echo $_link->getTitle() ?>" <?php echo $_link->getAParams() ?>><i class="fa fa-caret-right"></i><?php echo $_link->getLabel() ?></a><?php echo $_link->getAfterText() ?></li>
			<?php endif;?>
		<?php endforeach; ?>
    </ul>
</div>