<div class="footerlist account col-12 col-sm-6 col-lg-2">
    <p>MY ACCOUNT</p>
    <ul>
        <li><a href=""><i class="fa fa-caret-right"></i>My Account</a></li>
        <li><a href=""><i class="fa fa-caret-right"></i>Order History</a></li>
        <li><a href=""><i class="fa fa-caret-right"></i>Wish List</a></li>
        <li><a href=""><i class="fa fa-caret-right"></i>Newsletter</a></li>
        <li><a href=""><i class="fa fa-caret-right"></i>Cart</a></li>
        <li><a href=""><i class="fa fa-caret-right"></i>CheckOut</a></li>
    </ul>
</div>